# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_1120.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QDesktopWidget, QApplication, QToolTip


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setStyleSheet("#MainWindow{border-image:url(img/背景1.png);}")  # 局部背景
        # MainWindow.setStyleSheet("#MainWindow {\n"
        #                      "    background-color: rgb(0, 0, 0);\n"
        #                      "}\n"
        #                      "#widget {\n"
        #                      "    background-color: rgb(255, 255, 255);\n"
        #                      "    border-radius: 20px;\n"
        #                      "}\n"
        #                      "#closeButton {\n"
        #                      "    border: none;\n"
        #                      "    background-color: rgb(255, 255, 255);\n"
        #                      "}\n"
        #                      "#closeButton:hover {\n"
        #                      "    color: white;\n"
        #                      "    background-color: rgb(232, 16, 16);\n"
        #                      "}")
        MainWindow.resize(400, 300)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_7.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px;");
        self.label_7.setObjectName("label")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_6.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px;");
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setAlignment(Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        # spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.verticalLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setMaximumSize(QtCore.QSize(30, 30))
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout.addWidget(self.closeButton)


        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_4.setStyleSheet(''' 
                     QPushButton
                     {text-align : center;
                     background-color : lightblue;
                     font: bold;
                     border-color: gray;
                     border-width: 2px;
                     border-radius: 10px;
                     padding: 6px;
                     height : 14px;
                     border-style: outset;
                     font : 14px;}
                     QPushButton:pressed
                     {text-align : center;
                     background-color : light gray;
                     font: bold;
                     border-color: gray;
                     border-width: 2px;
                     border-radius: 10px;
                     padding: 6px;
                     height : 14px;
                     border-style: outset;
                     font : 14px;}
                     ''')
        self.pushButton_4.setObjectName("pushButton_4")
        # 按键提示信息
        QToolTip.setFont(QFont('SansSerif', 12))
        self.pushButton_4.setToolTip('人脸入库')
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_5.setStyleSheet('''
                     QPushButton
                     {text-align : center;
                     background-color : lightblue;
                     font: bold;
                     border-color: gray;
                     border-width: 2px;
                     border-radius: 10px;
                     padding: 6px;
                     height : 14px;
                     border-style: outset;
                     font : 14px;}
                     QPushButton:pressed
                     {text-align : center;
                     background-color : light gray;
                     font: bold;
                     border-color: gray;
                     border-width: 2px;
                     border-radius: 10px;
                     padding: 6px;
                     height : 14px;
                     border-style: outset;
                     font : 14px;}
                     ''');
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_11.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px;");
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_12.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px;");
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_13.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px;");
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_14.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px;");
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setAlignment(Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(Qt.AlignCenter)
        # self.label_5.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px;");
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_4.setObjectName("label_4")



        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1) # 位置：第1行，第1列  占用1行4列
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", ""))
        self.label_6.setText(_translate("MainWindow", ""))
        self.label_1.setText(_translate("MainWindow", "摄像头"))
        self.label_2.setText(_translate("MainWindow", "人脸库"))
        self.pushButton_4.setText(_translate("MainWindow", "人脸入库"))
        self.pushButton_5.setText(_translate("MainWindow", "人脸识别"))
        self.label_11.setText(_translate("MainWindow", ""))
        self.label_12.setText(_translate("MainWindow", ""))
        self.label_13.setText(_translate("MainWindow", ""))
        self.label_14.setText(_translate("MainWindow", ""))
        self.label_15.setText(_translate("MainWindow", "相似度1"))
        self.label_16.setText(_translate("MainWindow", "相似度2"))
        self.label_17.setText(_translate("MainWindow", "相似度3"))
        self.label_18.setText(_translate("MainWindow", "相似度4"))
        self.label_5.setText(_translate("MainWindow", ""))
        self.label_3.setText(_translate("MainWindow", "校门关闭"))
        self.label_4.setText(_translate("MainWindow", "图标"))
        self.closeButton.setText(_translate("MainWindow", "X"))
        # self.plainTextEdit.setPlainText(_translate("MainWindow", "其他内容"))

    # def center(self):  # 定义一个函数使得窗口居中显示
    #     # 获取屏幕坐标系
    #     screen = QDesktopWidget().screenGeometry()
    #     # 获取窗口坐标系
    #     size = self.geometry()
    #     newLeft = (screen.width() - size.width()) / 2
    #     newTop = (screen.height() - size.height()) / 2
    #     self.move(int(newLeft), int(newTop))
    #     # 获取桌面属性
    #     # desktop = QApplication.desktop()
    #     # 通过桌面的宽和高来比例位置显示
    #     # Dialog.move(desktop.width() * 0.6, desktop.height() * 0.7)

